version: '3.8'

services:
  app:
    build: .
    container_name: todo-api-app
    ports:
      - "8080:8080"
    depends_on:
      - db
    env_file:
      - .env
    #volumes:
    #  - .:/app
    restart: always

  db:
    image: mysql:8.0
    container_name: todo-api-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: todo_db
      MYSQL_USER: todo_user
      MYSQL_PASSWORD: todopass
    volumes:
      - db-data:/var/lib/mysql
    restart: always

volumes:
  db-data:
